In [1]:
import numpy as np
import pandas as pd
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler #for Scaling the data mostly used for SVMs
from sklearn.svm import LinearSVC

In [2]:
acc_data=pd.read_csv("/Users/rohithmovva/Downloads/HMP_Dataset/Featured_Data.csv", thousands = ',')

In [3]:
acc_data.describe()

,Unnamed: 0,meanx,meany,meanz,medianx,mediany,medianz,corxy,coryz,corxz,...,varz,varxy,varyz,varxz,fftxmax,fftymax,fftzmax,specenergy,xbtwnzandy,xless10
count,705.000000,705.000000,705.000000,705.000000,705.000000,705.000000,705.000000,705.000000,705.000000,705.000000,...,705.000000,705.000000,705.000000,705.000000,705.000000,705.000000,705.000000,705.000000,705.000000,705.000000
mean,353.000000,22.998357,38.142888,42.384578,22.143262,38.361702,42.235461,0.016611,-0.021365,0.417908,...,31.852838,0.278387,-0.624970,25.716139,9716.960284,16815.782979,18380.541844,237.799134,0.106467,0.057171
std,203.660256,8.101492,3.398680,5.862418,8.905440,3.708629,6.969894,0.519873,0.459669,0.489632,...,30.116090,22.073396,13.201241,30.371453,5681.381211,10437.291697,10133.332938,44.080211,0.162739,0.080414
min,1.000000,11.614815,21.555556,28.179028,12.000000,18.000000,30.000000,-0.968655,-0.923741,-0.855280,...,0.896002,-94.370362,-57.625764,-79.047175,2319.000000,4916.000000,5062.000000,146.404223,0.000000,0.000000
25%,177.000000,15.934156,36.191377,36.561151,14.000000,36.000000,35.000000,-0.409825,-0.425712,0.020413,...,5.566520,-9.538993,-7.970426,0.141544,5330.000000,10668.000000,12202.000000,209.761549,0.000000,0.000000
50%,353.000000,21.949924,37.907749,42.314917,19.000000,38.000000,42.000000,0.004021,0.029697,0.612319,...,19.174499,0.063929,0.207862,16.037004,9187.000000,15053.000000,16707.000000,230.304196,0.010929,0.014523
75%,529.000000,30.392197,40.441860,47.866817,31.000000,40.000000,49.000000,0.479136,0.314526,0.849181,...,55.555329,12.635864,5.704525,49.836728,12599.000000,18277.000000,21815.000000,258.306485,0.188153,0.103753
max,705.000000,41.209360,48.274510,52.744409,45.000000,52.000000,53.000000,0.947640,0.937039,0.978793,...,178.834702,114.456539,77.569484,106.983482,54408.000000,113763.000000,112210.000000,453.462807,0.901695,0.302030

In [4]:
acc_data.head()

,Unnamed: 0,vol,meanx,meany,meanz,medianx,mediany,medianz,corxy,coryz,...,varxy,varyz,varxz,fftxmax,fftymax,fftzmax,specenergy,xbtwnzandy,xless10,HMPactivity
0,1,f1,11.818519,36.744444,33.133333,13.0,37.0,33.0,-0.288347,0.015871,...,-3.001941,0.071375,-0.696902,3191,9921,8946,173.080777,0.0,0.248148,Climb_stairs
1,2,f1,11.811111,36.811111,32.651852,13.0,37.0,33.0,-0.310059,0.207788,...,-2.675217,0.904254,-0.560430,3189,9939,8816,167.026506,0.0,0.222222,Climb_stairs
2,3,f1,12.303704,38.555556,33.666667,14.0,38.0,33.0,-0.409825,0.208383,...,-3.377530,0.758364,-0.634449,3322,10410,9090,164.360428,0.0,0.233333,Climb_stairs
3,4,f1,11.662963,35.044444,34.637037,13.0,35.0,34.0,-0.107748,0.149019,...,-0.832549,0.462288,0.007325,3149,9462,9352,161.205369,0.0,0.270370,Climb_stairs
4,5,f1,11.614815,34.892593,34.640741,13.0,35.0,34.0,-0.070808,0.338446,...,-0.654908,1.797701,-1.146331,3136,9421,9353,172.425779,0.0,0.266667,Climb_stairs

In [5]:
type(acc_data)

pandas.core.frame.DataFrame

In [6]:
np.random.seed(42)
shuffle_index = np.random.permutation(len(acc_data))
acc_data=acc_data.iloc[shuffle_index]
acc_data.head()

,Unnamed: 0,vol,meanx,meany,meanz,medianx,mediany,medianz,corxy,coryz,...,varxy,varyz,varxz,fftxmax,fftymax,fftzmax,specenergy,xbtwnzandy,xless10,HMPactivity
478,479,f4,23.242812,38.479233,45.146965,30.0,39.0,51.0,0.583513,0.645036,...,13.274289,12.813959,69.102021,7275,12044,14131,221.420417,0.0,0.012780,Sitdown_chair
81,82,m6,12.097252,34.300211,35.099366,13.0,34.0,35.0,-0.118364,0.101342,...,-0.461461,0.188326,-0.541464,5722,16224,16602,180.836495,0.0,0.133192,Climb_stairs
77,78,m6,12.119205,34.328918,34.320088,12.0,34.0,34.0,-0.524884,0.052872,...,-2.563632,0.128997,-0.040453,5490,15551,15547,180.826542,0.0,0.103753,Climb_stairs
208,209,f1,15.315951,40.058282,37.610429,14.0,40.0,35.0,0.257075,0.174564,...,5.086144,5.050467,19.218849,4993,13059,12261,253.344761,0.0,0.049080,Getup_bed
319,320,f1,28.662366,35.595699,49.298925,30.0,37.0,49.0,0.902103,0.043835,...,44.115355,1.138357,2.308041,13328,16552,22924,241.428603,0.0,0.000000,Pour_water

In [7]:
#x=acc_data.iloc[:,2:23]
#y=(acc_data["HMPactivity"] == 'Climb_stairs').astype(np.float64)
#y=acc_data["HMPactivity"]
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(acc_data.iloc[:,2:23], acc_data["HMPactivity"],test_size=.2,random_state=42)

In [8]:
print(x_train.shape,x_test.shape,y_train.shape,y_test.shape)

(564, 21) (141, 21) (564,) (141,)

In [9]:
y_train.unique()

array(['Climb_stairs', 'Standup_chair', 'Drink_glass', 'Sitdown_chair',
       'Walk', 'Getup_bed', 'Pour_water'], dtype=object)

In [10]:
x_train.head()

,meanx,meany,meanz,medianx,mediany,medianz,corxy,coryz,corxz,varx,...,varz,varxy,varyz,varxz,fftxmax,fftymax,fftzmax,specenergy,xbtwnzandy,xless10
97,15.042129,37.660754,36.137472,14.0,37.0,35.0,0.274861,0.547882,0.754330,67.449332,...,33.109948,6.867657,9.591185,35.647529,6784,16985,16298,260.573732,0.002217,0.172949
530,19.651961,39.338235,39.769608,14.5,37.0,35.0,-0.020766,-0.089969,0.915905,79.193543,...,76.276707,-0.999928,-4.251739,71.185429,4009,8025,8113,230.304196,0.034314,0.004902
167,36.427609,38.592593,50.619529,35.0,41.0,51.0,-0.874617,0.007854,-0.061722,11.475316,...,0.993266,-15.298173,0.040415,-0.208379,10819,11462,15034,190.047865,0.323232,0.000000
408,22.389313,41.549618,44.938931,26.0,42.0,49.0,0.317933,0.412258,0.921438,37.531885,...,49.442396,5.615150,8.356900,39.693188,2933,5443,5887,202.421135,0.000000,0.007634
605,12.915385,36.765812,34.766667,12.0,36.0,34.0,0.504918,0.441822,0.743056,38.616444,...,18.307357,8.631151,5.200228,19.756972,15111,43016,40677,303.270293,0.000000,0.209402

In [11]:
y_test.values

array(['Getup_bed', 'Walk', 'Getup_bed', 'Climb_stairs', 'Drink_glass',
       'Pour_water', 'Sitdown_chair', 'Sitdown_chair', 'Sitdown_chair',
       'Climb_stairs', 'Walk', 'Climb_stairs', 'Climb_stairs',
       'Standup_chair', 'Sitdown_chair', 'Standup_chair', 'Drink_glass',
       'Getup_bed', 'Standup_chair', 'Standup_chair', 'Pour_water',
       'Climb_stairs', 'Pour_water', 'Drink_glass', 'Climb_stairs',
       'Getup_bed', 'Climb_stairs', 'Climb_stairs', 'Standup_chair',
       'Drink_glass', 'Walk', 'Walk', 'Pour_water', 'Standup_chair',
       'Sitdown_chair', 'Standup_chair', 'Climb_stairs', 'Climb_stairs',
       'Standup_chair', 'Getup_bed', 'Getup_bed', 'Standup_chair',
       'Pour_water', 'Sitdown_chair', 'Drink_glass', 'Drink_glass',
       'Climb_stairs', 'Getup_bed', 'Walk', 'Drink_glass',
       'Sitdown_chair', 'Climb_stairs', 'Drink_glass', 'Drink_glass',
       'Drink_glass', 'Getup_bed', 'Standup_chair', 'Walk',
       'Climb_stairs', 'Walk', 'Walk', 'Drink_glass', 'Climb_stairs',
       'Drink_glass', 'Drink_glass', 'Getup_bed', 'Drink_glass',
       'Drink_glass', 'Sitdown_chair', 'Standup_chair', 'Getup_bed',
       'Sitdown_chair', 'Pour_water', 'Sitdown_chair', 'Sitdown_chair',
       'Climb_stairs', 'Sitdown_chair', 'Sitdown_chair', 'Climb_stairs',
       'Standup_chair', 'Pour_water', 'Getup_bed', 'Drink_glass',
       'Climb_stairs', 'Getup_bed', 'Getup_bed', 'Pour_water',
       'Climb_stairs', 'Climb_stairs', 'Pour_water', 'Pour_water',
       'Drink_glass', 'Climb_stairs', 'Drink_glass', 'Getup_bed',
       'Sitdown_chair', 'Drink_glass', 'Getup_bed', 'Standup_chair',
       'Sitdown_chair', 'Standup_chair', 'Sitdown_chair', 'Climb_stairs',
       'Climb_stairs', 'Standup_chair', 'Pour_water', 'Drink_glass',
       'Sitdown_chair', 'Climb_stairs', 'Standup_chair', 'Getup_bed',
       'Walk', 'Drink_glass', 'Standup_chair', 'Drink_glass',
       'Climb_stairs', 'Standup_chair', 'Drink_glass', 'Getup_bed',
       'Standup_chair', 'Getup_bed', 'Sitdown_chair', 'Climb_stairs',
       'Walk', 'Climb_stairs', 'Drink_glass', 'Pour_water', 'Getup_bed',
       'Getup_bed', 'Climb_stairs', 'Sitdown_chair', 'Pour_water',
       'Pour_water', 'Sitdown_chair', 'Getup_bed', 'Standup_chair',
       'Climb_stairs', 'Walk', 'Sitdown_chair', 'Pour_water',
       'Standup_chair'], dtype=object)

In [12]:
## LinearSVC which uses One-Vs-Rest classification for Multiclass Classification
svm_clf = Pipeline([
        ("scaler", StandardScaler()),
        ("linear_svc", LinearSVC(C=1, loss="hinge", random_state=42)),
    ])

In [13]:
y_pred_t_linear=svm_clf.fit(x_train, y_train).predict(x_train)

In [14]:
from sklearn.metrics import accuracy_score, confusion_matrix
activity={0:"Climb_stairs",1:"Drink_glass",2:"Getup_bed",3:"Pour_water",4:"Sitdown_chair",5:"Standup_chair",6:"Walk"}
labels=["Climb_stairs","Drink_glass","Getup_bed","Pour_water","Sitdown_chair","Standup_chair","Walk"]
print(pd.DataFrame(confusion_matrix(y_train.values,y_pred_t_linear,labels=labels), index=activity, columns=activity))
print('Accuracy: ' + str(accuracy_score(y_train.values, y_pred_t_linear)))

    0   1   2   3   4   5   6
0  72   0   1   0   0   0   1
1   0  76   0   0   0   0   0
2   0   1  70   0   6   3   0
3   0   0   0  85   0   0   0
4   0   0   3   0  65  11   0
5   1   1   1   1   5  72   0
6   8   0   0   0   1   0  80
Accuracy: 0.9219858156028369

In [15]:
y_pred_linear=svm_clf.fit(x_train, y_train).predict(x_test)

In [16]:
print(pd.DataFrame(confusion_matrix(y_test.values,y_pred_linear,labels=labels), index=activity, columns=activity))
print('Accuracy: ' + str(accuracy_score(y_test.values, y_pred_linear)))

    0   1   2   3   4   5  6
0  27   0   0   0   0   0  1
1   0  23   0   1   0   0  0
2   0   0  18   0   2   1  0
3   0   0   0  15   0   0  0
4   0   0   1   0  17   3  0
5   0   0   2   1   0  18  0
6   2   0   0   0   0   0  9
Accuracy: 0.900709219858156

In [18]:
## SVC with Kernel Linear uses One-Vs-One Classification
from sklearn.svm import SVC
svm_clf_l = Pipeline([
        ("scaler", StandardScaler()),
        ("svc_l", SVC(kernel="linear",C=1, random_state=42)),
    ])

In [19]:
y_pred_t_l=svm_clf_l.fit(x_train, y_train).predict(x_train)

In [20]:
print(pd.DataFrame(confusion_matrix(y_train.values,y_pred_t_l,labels=labels), index=activity, columns=activity))
print('Accuracy: ' + str(accuracy_score(y_train.values, y_pred_t_l)))

    0   1   2   3   4   5   6
0  74   0   0   0   0   0   0
1   0  76   0   0   0   0   0
2   0   0  78   0   2   0   0
3   0   0   0  85   0   0   0
4   0   0   4   0  68   7   0
5   0   0   2   0   6  73   0
6   6   0   0   0   0   0  83
Accuracy: 0.9521276595744681

In [21]:
y_pred_l=svm_clf_l.fit(x_train, y_train).predict(x_test)

In [22]:
print(pd.DataFrame(confusion_matrix(y_test.values,y_pred_l,labels=labels), index=activity, columns=activity))
print('Accuracy: ' + str(accuracy_score(y_test.values, y_pred_l)))

    0   1   2   3   4   5  6
0  27   0   0   0   0   0  1
1   0  23   0   1   0   0  0
2   0   0  19   0   2   0  0
3   0   0   0  15   0   0  0
4   0   0   1   0  18   2  0
5   0   0   3   0   0  18  0
6   2   0   0   0   0   0  9
Accuracy: 0.9148936170212766

In [31]:
poly_kernel_svm_clf = Pipeline([
        ("scaler", StandardScaler()),
        ("svm_clf", SVC(kernel="poly", degree=2, coef0=1, C=1))
    ])

In [32]:
y_pred_t_poly=poly_kernel_svm_clf.fit(x_train,y_train).predict(x_train)
print(pd.DataFrame(confusion_matrix(y_train.values,y_pred_t_poly,labels=labels), index=activity, columns=activity))
print('Accuracy: ' + str(accuracy_score(y_train.values, y_pred_t_poly)))

    0   1   2   3   4   5   6
0  74   0   0   0   0   0   0
1   0  76   0   0   0   0   0
2   0   0  76   0   4   0   0
3   0   0   0  85   0   0   0
4   0   0   3   0  67   9   0
5   0   0   1   1   5  74   0
6   7   0   0   0   0   0  82
Accuracy: 0.9468085106382979

In [33]:
y_pred_poly=poly_kernel_svm_clf.fit(x_train,y_train).predict(x_test)

In [34]:
activity={0:"Climb_stairs",1:"Drink_glass",2:"Getup_bed",3:"Pour_water",4:"Sitdown_chair",5:"Standup_chair",6:"Walk"}
print(pd.DataFrame(confusion_matrix(y_test.values,y_pred_poly,labels=labels), index=activity, columns=activity))
print('Accuracy: ' + str(accuracy_score(y_test.values, y_pred_poly)))

    0   1   2   3   4   5   6
0  27   0   0   0   0   0   1
1   0  23   0   1   0   0   0
2   0   0  19   0   2   0   0
3   0   0   0  15   0   0   0
4   0   0   1   0  18   2   0
5   0   0   2   0   0  19   0
6   1   0   0   0   0   0  10
Accuracy: 0.9290780141843972